export const MY_POKEMONS_ADD = "MY_POKEMONS_ADD";
export const MY_POKEMONS_REMOVE = "MY_POKEMONS_REMOVE";

export const POKEMONS_LOADING = "POKEMONS_LOADING";
export const POKEMONS_SHOW = "POKEMONS_SHOW";
export const POKEMONS_SHOW_ITEM = "POKEMONS_SHOW_ITEM";
